# -*- coding: utf-8 -*-
"""credit card fraud

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwWES_kJVsDu2tzz7xAPhjIKfgCzP4-h
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

# train_models.py
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import joblib

# Load dataset
data = pd.read_csv("/kaggle/input/creditcardfraud/creditcard.csv")

# Features and target
X = data.drop('Class', axis=1)
y = data['Class']
X_0= data[data['Class']==0].iloc[:492]

X_0 = X_0.drop('Class', axis=1)

y_0 = y[data['Class']==0].iloc[:492]
X_1= data[data['Class']==1]
X_1 = X_1.drop('Class', axis=1)

y_1= y[data['Class']==1]
# TODO: Train-test split
X_train_0, X_test_0, y_train_0, y_test_0 = train_test_split(X_0, y_0, test_size=0.2, random_state=42)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.2, random_state=42)
X_train = pd.merge(X_train_0,X_train_1,how='outer')

X_test = pd.merge(X_test_0,X_test_1,how='outer')

y_train = pd.merge(y_train_0,y_train_1,how='outer')

y_test = pd.merge(y_test_0,y_test_1,how='outer')

# TODO: Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(len(X_train_scaled))
print(len(y_train))
# Fill these after preprocessing
train_samples = X_train_scaled.shape[0]       # Number of training samples
test_samples = X_test_scaled.shape[0]       # Number of test samples
train_test_ratio = 0.8  # e.g., 0.8 for 80-20 split

print(f"Train samples: {train_samples}")
print(f"Test samples: {test_samples}")
print(f"Split ratio: {train_test_ratio:.1%}")


# Define models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "kNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "XGBoost": xgb.XGBClassifier(use_label_encoder=False, eval_metric="logloss")
}

results = []

# Train and evaluate
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1] if hasattr(model, "predict_proba") else y_pred

    metrics = {
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "AUC": roc_auc_score(y_test, y_prob),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "MCC": matthews_corrcoef(y_test, y_pred)
    }
    results.append(metrics)
    import os

    # Define the path for the new folder
    folder_path = "/content/sample_data/model"

    # Use os.makedirs() to create the folder and any missing parent folders
    # exist_ok=True prevents an error if the directory already exists (Python 3.2+)
    try:
        os.makedirs(folder_path, exist_ok=True)
        print(f"Directory '{folder_path}' created or already exists.")
    except PermissionError:
        print(f"Error: Lack of permission to create directory '{folder_path}'.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


    # Save model
    joblib.dump(model, f"/content/sample_data/model/{name.replace(' ', '_').lower()}.pkl")

# Results table
results_df = pd.DataFrame(results)
print(results_df)
results_df.to_csv("model_results.csv", index=False)

